Repository Varying-Vagrant-Vagrants/vvv-utilities, pull requests merged in 2019-12, with the labels that each got.

#48 Fix shyaml site name escaping in the TLS CA
  tls-ca/provision.sh
Labels: bug

#47 fix super user root warning when provisioning webgrind
  webgrind/provision.sh
Labels: bug

#42 Update composer in xhgui during provision
  tideways/provision.sh
Labels: enhancement

#49 change expiration from 10 years to 200 days
  tls-ca/provision.sh
Labels: bug

#50 TLS CA improvements
  tls-ca/provision.sh
Labels: enhancement

#51 MongoDB PHP fixes
  mongodb/provision.sh
Labels: bug, enhancement
