Repository Varying-Vagrant-Vagrants/vvv-utilities, pull requests merged in 2019-11, with the labels that each got.

#35 Add WpCli-dev utilities
  wpcli-dev/provision.sh
Labels: enhancement

#40 Adjust Tideways loading
  tideways/tideways-header.php
Labels: bug, enhancement

#41 Update PHPMyAdmin
  phpmyadmin/provision.sh
Labels: enhancement

#43 add PHP 7.4 to the list on mongodb PHP extensions to install
  mongodb/provision.sh
Labels: bug
